artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  climate_data_url: https://climate.nasa.gov/api/temperature-data
  social_data_url: https://api.github.com/repos/nasa/climate-data
  climate_data_path: artifacts/data_ingestion/climate_data.csv
  social_data_path: artifacts/data_ingestion/social_data.csv
  raw_data_path: artifacts/data_ingestion/raw_data
  unzip_dir: artifacts/data_ingestion/unzipped

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/unzipped
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  tokenizer_name: textblob
  max_features: 5000
  sequence_length: 100
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  transformed_train_path: artifacts/data_transformation/train.csv
  transformed_test_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: climate_predictor
  trained_model_path: artifacts/model_trainer/model.pkl
  model_metrics_path: artifacts/model_trainer/metrics.json

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json
  